-- Safe Supabase schema for Shanchuan Visual Archive.
-- Run in Supabase SQL Editor.
-- This creates tables, indexes, default data, and the public media bucket.
-- It intentionally does NOT grant anonymous write access.

create table if not exists public.settings (
  key text primary key,
  value text default '',
  updated_at timestamptz default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text default '',
  cover_image text default '',
  sort_order integer default 0,
  is_primary boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text default '',
  slug text not null unique,
  category_id bigint references public.categories(id) on delete set null,
  description text default '',
  cover_image text default '',
  year text default '',
  location text default '',
  is_featured boolean default false,
  is_recommended boolean default false,
  is_series boolean default false,
  series_style text default '',
  status text default 'draft' check (status in ('draft','published')),
  tags text default '',
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  title text default '',
  description text default '',
  file_path text not null,
  storage_path text default '',
  original_name text default '',
  file_type text default '',
  mime_type text default '',
  size bigint default 0,
  media_type text default 'image',
  tags text default '',
  camera text default '',
  lens text default '',
  aperture text default '',
  shutter_speed text default '',
  iso text default '',
  captured_at text default '',
  is_hero boolean default false,
  is_selected boolean default false,
  is_cover boolean default false,
  show_in_database boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  created_at timestamptz default now()
);

create table if not exists public.project_tags (
  project_id bigint not null references public.projects(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (project_id, tag_id)
);

create table if not exists public.media_tags (
  media_id bigint not null references public.media(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (media_id, tag_id)
);

create index if not exists idx_categories_primary_sort on public.categories(is_primary, sort_order, id);
create index if not exists idx_projects_status_sort on public.projects(status, sort_order, id);
create index if not exists idx_projects_category on public.projects(category_id);
create index if not exists idx_projects_series on public.projects(is_series, is_recommended, sort_order);
create index if not exists idx_media_project on public.media(project_id, sort_order, id);
create index if not exists idx_media_category on public.media(category_id, sort_order, id);
create index if not exists idx_media_database on public.media(show_in_database, is_selected, sort_order, id);
create index if not exists idx_media_hero on public.media(is_hero, updated_at desc, sort_order, id desc);

insert into public.settings (key, value, updated_at) values
  ('site_name','山川行止',now()),
  ('hero_title','山川行止',now()),
  ('hero_subtitle','摄影 / 平面设计 / 空间 / 日常研究',now()),
  ('hero_media','/assets/hero-default.jpg',now()),
  ('hero_media_type','image',now()),
  ('contact_email','hello@example.com',now())
on conflict (key) do nothing;

insert into public.categories (name, slug, description, sort_order, is_primary) values
  ('摄影','photo','人物、现场、城市、产品与观看方式。',1,true),
  ('平面','graphic','字体、版式、品牌与视觉系统。',2,true),
  ('空间','space','尺度、材质、光线与空间秩序。',3,true),
  ('AI','ai','图像生成、风格测试与概念草图。',4,true),
  ('其他','other','日常实验、手绘、厨艺、手工与未完成想法。',5,true)
on conflict (slug) do nothing;

-- Idempotent, lossless migration for installations that previously used a
-- top-level `product` category. Discover the real IDs instead of assuming a
-- seed value, move all references first, and only then remove the old row.
do $$
declare
  photo_category_id bigint;
  product_category_id bigint;
begin
  select id into photo_category_id from public.categories where slug = 'photo' limit 1;
  select id into product_category_id from public.categories where slug = 'product' limit 1;
  if photo_category_id is not null and product_category_id is not null then
    update public.projects set category_id = photo_category_id, updated_at = now() where category_id = product_category_id;
    update public.media set category_id = photo_category_id, updated_at = now() where category_id = product_category_id;
    delete from public.categories where id = product_category_id;
  end if;
end $$;

insert into public.tags (name, slug) values
  ('3D','3d'),('视频','video'),('厨艺','cooking'),('手绘','drawing'),('手工','craft'),
  ('建模','modeling'),('空间设计','space-design'),('摄影','photography'),('品牌','branding'),('AI生成','ai-generated')
on conflict (slug) do nothing;

insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do update set public = true;

-- For production, prefer RLS + a server-only service role key for admin writes.
-- If you explicitly accept anon-key write access, create narrow policies separately.
