"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
type Settings={provider:string;model:string;status:string;source:string;supported_tasks:string[];runtime_mode:string};
type Connector={connector_id:string;display_name:string;ready:boolean;authentication_mode:string;configured_model:string;safe_status_message:string};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`/api/novel/${path}`,{...init,headers:{"content-type":"application/json",...init?.headers}});const data=await response.json();if(!response.ok)throw new Error(data.message??"请求失败");return data;}
export default function ModelsPage(){
 const [settings,setSettings]=useState<Settings|null>(null),[connectors,setConnectors]=useState<Connector[]>([]),[provider,setProvider]=useState("fake"),[model,setModel]=useState(""),[note,setNote]=useState("加载中…"),[testing,setTesting]=useState(false);
 async function load(){try{const [item,items]=await Promise.all([api<Settings>("settings/models"),api<Connector[]>("connectors")]);setSettings(item);setConnectors(items);setProvider(item.provider);setModel(item.model);setNote("连接状态仅做本机配置检查；不会显示密钥或本机路径。")}catch(error){setNote(error instanceof Error?error.message:"加载失败")}}
 useEffect(()=>{void load()},[]);
 async function save(event:FormEvent){event.preventDefault();try{const item=await api<Settings>("settings/models",{method:"PUT",body:JSON.stringify({provider,model})});setSettings(item);setNote("系统默认模型已保存。") }catch(error){setNote(error instanceof Error?error.message:"保存失败")}}
 async function testCodex(){if(!window.confirm("这会发起一次很短的真实 Codex 调用。是否继续？"))return;setTesting(true);try{const result=await api<{safe_message:string;response_preview:string}>("providers/codex/test",{method:"POST",body:JSON.stringify({confirmed:true})});setNote(`${result.safe_message}：${result.response_preview}`);await load()}catch(error){setNote(error instanceof Error?error.message:"测试失败")}finally{setTesting(false)}}
 return <main><header><div><p className="eyebrow">MODEL CENTER</p><h1>模型连接</h1></div><Link href="/novel-studio">返回控制中心</Link></header><p className="notice">{note}</p><section className="panel">{settings&&<div className="item"><b>{settings.status} · {settings.runtime_mode}</b><small>来源：{settings.source}；支持：{settings.supported_tasks.join("、")}</small></div>}<div className="connectorCards">{connectors.map(item=><button type="button" className={provider===item.connector_id?"connector selected":"connector"} key={item.connector_id} onClick={()=>setProvider(item.connector_id)}><b>{item.display_name}</b><small>{item.ready?"已就绪":"未就绪"} · {item.configured_model}</small><small>{item.safe_status_message}</small></button>)}</div><form onSubmit={save}><label>当前连接<select value={provider} onChange={e=>setProvider(e.target.value)}>{connectors.map(item=><option key={item.connector_id} value={item.connector_id}>{item.display_name}</option>)}</select></label><label>模型名称<input value={model} onChange={e=>setModel(e.target.value)} placeholder="CLI 默认模型"/></label><button className="primary">保存系统默认模型</button></form><button className="secondary" disabled={testing} onClick={()=>void testCodex()}>{testing?"正在测试…":"测试 Codex 真实连接"}</button><p className="notice">真实测试只会在你点击并确认后执行；失败不会自动切换为模拟模式。</p></section></main>;
}
