export type InspirationChapter = { id: string; title: string; english: string; keywords?: string[] };
export type InspirationChannel = { id: string; title: string; english: string; chapters: InspirationChapter[] };
export type InspirationTree = { channels: InspirationChannel[] };
export type InspirationResourceAssignment = { channel: string; chapter: string; title?: string; description?: string; source_url?: string; tags?: string };
export type InspirationResourceMap = Record<string, InspirationResourceAssignment>;
const chapters = (items: Array<[string, string, string[]]>): InspirationChapter[] => items.map(([id, title, keywords]) => ({ id, title, english: id.toUpperCase(), keywords }));
export const defaultInspirationTree: InspirationTree = { channels: [
  { id: "photo", title: "\u6444\u5f71", english: "PHOTOGRAPHY", chapters: chapters([["humanity", "\u4eba\u6587", ["humanity", "\u4eba\u6587", "\u4eba\u7269", "street", "people"]], ["landscape", "\u98ce\u5149", ["landscape", "\u98ce\u5149", "\u98ce\u666f", "\u81ea\u7136", "city"]], ["news", "\u65b0\u95fb", ["news", "\u65b0\u95fb", "\u7eaa\u5b9e", "event"]], ["portrait", "\u5199\u771f", ["portrait", "\u5199\u771f", "\u8096\u50cf", "\u4eba\u50cf"]], ["macro", "\u5fae\u8ddd", ["macro", "\u5fae\u8ddd", "closeup", "detail"]]]) },
  { id: "graphic", title: "\u5e73\u9762", english: "GRAPHIC", chapters: chapters([["type", "\u5b57\u4f53", ["type", "typography", "\u5b57\u4f53", "\u6392\u5370"]], ["branding", "\u54c1\u724c", ["brand", "branding", "\u54c1\u724c", "identity"]], ["editorial", "\u7f16\u8f91", ["editorial", "\u7f16\u8f91", "book", "booklet"]], ["poster", "\u6d77\u62a5", ["poster", "\u6d77\u62a5", "campaign"]], ["illustration", "\u63d2\u753b", ["illustration", "\u63d2\u753b", "drawing"]]]) },
  { id: "space", title: "\u7a7a\u95f4", english: "SPACE", chapters: chapters([["model", "3D\u5efa\u6a21", ["3d", "model", "\u5efa\u6a21", "render"]], ["interior", "\u5ba4\u5185", ["interior", "\u5ba4\u5185", "room"]], ["architecture", "\u5efa\u7b51", ["architecture", "\u5efa\u7b51", "building"]], ["material", "\u6750\u8d28", ["material", "\u6750\u8d28", "texture"]], ["installation", "\u88c5\u7f6e", ["installation", "\u88c5\u7f6e", "exhibition"]]]) },
  { id: "ai", title: "AI", english: "GENERATIVE", chapters: chapters([["image", "\u56fe\u50cf", ["image", "\u56fe\u50cf", "visual"]], ["concept", "\u6982\u5ff5", ["concept", "\u6982\u5ff5"]], ["prompt", "\u63d0\u793a\u8bcd", ["prompt", "\u63d0\u793a\u8bcd"]], ["experiment", "\u5b9e\u9a8c", ["experiment", "\u5b9e\u9a8c", "test"]], ["workflow", "\u5de5\u4f5c\u6d41", ["workflow", "\u5de5\u4f5c\u6d41", "process"]]]) },
  { id: "other", title: "\u5176\u4ed6", english: "OTHER", chapters: chapters([["hand-drawn", "\u624b\u7ed8", ["hand", "drawing", "\u624b\u7ed8", "sketch"]], ["cooking", "\u53a8\u827a", ["cooking", "food", "\u53a8\u827a"]], ["craft", "\u624b\u5de5", ["craft", "\u624b\u5de5", "making"]], ["video", "\u89c6\u9891", ["video", "\u89c6\u9891", "film"]], ["daily", "\u65e5\u5e38", ["daily", "\u65e5\u5e38", "life"]]]) }
] };
export function parseInspirationTree(value: unknown): InspirationTree { try { const parsed = JSON.parse(String(value || "")); if (Array.isArray(parsed?.channels) && parsed.channels.length) return parsed; } catch {} return defaultInspirationTree; }
export function parseInspirationResourceMap(value: unknown): InspirationResourceMap { try { const parsed = JSON.parse(String(value || "{}")); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : {}; } catch { return {}; } }
